name: Deploy to AWS

on:
  push:
    branches:
    - main

function does_lambda_exist()
{
  aws lambda get-function --function-name $1 > /dev/null 2>&1
  if [ 0 -eq $? ]; then
    echo "Lambda '$1' exists"
  else
    echo "Lambda '$1' does not exist"
  fi
}

does_lambda_exist my_lambda_fn_name

jobs:
  # JOB 01
  Deploying_functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set flag from Commit
        env:
          FUNCTION_EXISTS: ${ aws lambda get-function --function-name testInvoke1 }
        run: |
          if ${FUNCTION_EXISTS} == true; then
            echo "EXISTE"
          else
            echo "NÃO EXISTE"
          fi

      - name: Deploy api-reports to AWS Lambda
        run: |
          zip -j reports.zip ./reports/*
          aws lambda update-function-code --function-name=api-reports --zip-file=fileb://reports.zip

      - name: Deploy api-files to AWS Lambda
        run: |
          zip -j files.zip ./files/*
          aws lambda update-function-code --function-name=api-files --zip-file=fileb://files.zip

      - name: Deploy api-notications to AWS Lambda
        run: |
          zip -j notications.zip ./notications/*
          aws lambda update-function-code --function-name=api-notications --zip-file=fileb://notications.zip

      - name: Deploy api-logs to AWS Lambda
        run: |
          zip -j logs.zip ./logs/*
          aws lambda update-function-code --function-name=api-logs --zip-file=fileb://logs.zip
