name: Deploy to AWS

on:
  push:
    branches:
    - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

    #  - name: Checking if lambda function exists
    #    if: ${{ aws lambda get-function --function-name my_lambda }}

      - name: "Set flag from Commit"
        env:
          COMMIT_VAR: ${{ contains(github.event.head_commit.message, '[commit var]') }}
        run: |
          if ${COMMIT_VAR} == true; then
            echo "flag=true" >> $GITHUB_ENV
            echo "flag set to true"
          else
            echo "flag=false" >> $GITHUB_ENV
            echo "flag set to false"
          fi

      - name: "Use flag if true"
        if: env.flag
        run: echo "Flag is available and true"
          


      - name: Deploy api-reports to AWS Lambda
        run: |
          zip -j reports.zip ./reports/*
          aws lambda update-function-code --function-name=api-reports --zip-file=fileb://reports.zip

      - name: Deploy api-files to AWS Lambda
        run: |
          zip -j files.zip ./files/*
          aws lambda update-function-code --function-name=api-files --zip-file=fileb://files.zip

      - name: Deploy api-notications to AWS Lambda
        run: |
          zip -j notications.zip ./notications/*
          aws lambda update-function-code --function-name=api-notications --zip-file=fileb://notications.zip

      - name: Deploy api-logs to AWS Lambda
        run: |
          zip -j logs.zip ./logs/*
          aws lambda update-function-code --function-name=api-logs --zip-file=fileb://logs.zip
