name: Deploy to AWS

on:
  push:
    branches:
    - main

jobs:
  # JOB 01
  Deploying_functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set flag from Commit
        env:
          FUNCTION_EXISTS: ${ aws lambda get-function --function-name testInvoke1 }
        run: |
          if ${FUNCTION_EXISTS} == true; then
            echo "EXISTE"
          else
            echo "NÃO EXISTE"
          fi
